import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";

const font = Roboto({ subsets: ["latin"], weight: ["100", "300", "400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
